# We probably want to provide the credentials using juju secrets
options:
  email:
    type: string
    description: Account email address.
  aws_access_key_id:
    type: string
    description: AWS Access Key ID
  aws_assume_role_arn:
    type: string
    description: AWS Assume Role ARN
    default: ""
  aws_hosted_zone_id:
    type: string
    description: To override the hosted zone ID
  aws_region:
    type: string
    description: AWS Region
  aws_profile:
    type: string
    description: AWS Profile
    default: ""
  aws_sdk_load_config:
    type: boolean
    default: false
    description: To retrieve the region from the CLI config file
  aws_secret_access_key:
    type: string
    description: AWS Secret Access Key
  aws_max_retries:
    type: int
    default: 5
    description: The number of maximum returns the service will use to make an individual API request
  aws_polling_interval:
    type: int
    default: 15
    description: Time between DNS propagation checks in seconds
  aws_propagation_timeout:
    type: int
    default: 3600
    description: Maximum waiting time for DNS propagation in seconds
  aws_shared_credentials_file:
    type: string
    description: AWS Shared Credentials File
  aws_ttl:
    type: int
    default: 120
    description: The TTL of the TXT record used for the DNS challenge