name: CI

on:
  push:
    branches: ["main"]

jobs:
  lint-report:
    name: Lint report
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e lint

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static

  unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install tox
        run: pip install tox
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Run tests using tox
        run: tox -e integration
      - name: Archive Tested Charm
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' }}
        with:
          name: tested-charm
          path: .tox/**/route53-lego-operator_ubuntu-22.04-amd64.charm
          retention-days: 5
  
  publish-charm:
    name: Publish Charm
    needs: integration-tests
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Fetch Tested Charm
        uses: actions/download-artifact@v3
        with:
          name: tested-charm
      - name: Move charm in current directory
        run: find ./ -name route53-lego-operator_ubuntu-22.04-amd64.charm -exec mv -t ./ {} \;
      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.0.0-rc
        id: channel
      - name: Upload charm to Charmhub edge channel
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMHUB_TOKEN }}"
        run: charmcraft upload ./route53-lego-operator_ubuntu-22.04-amd64.charm --release ${{ steps.channel.outputs.name }}
        id: upload
      - name: Chmod charmcraft logs
        if: steps.upload.conclusion == 'failure'
        run: |
          sudo chmod -R 777 /root/snap/charmcraft/common/cache/charmcraft/log/
      - name: Archive charmcraft logs
        if: steps.upload.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-upload-logs
          path: /root/snap/charmcraft/common/cache/charmcraft/log/*.log
